kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim-{{ template "jupyter-r-nbk.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}