kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim-{{ template "jupyter-python-nbk.fullname" . }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi