apiVersion: v1
appVersion: "1.0"
description: Trifacta is a data preparation platform that empowers analytics champions and data engineers to explore, assess and refine data for analysis.
name: trifacta
version: 0.1.0
keywords:
  - trifacta
home: https://www.trifacta.com/
maintainers:
  - name: trifacta
    mail: team@trifacta.com
