kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-pv-claim-{{ template "dataiku-dss.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}